name: Continuous Integration

on:
  workflow_call: 

  # push:
  #  branches:
  #    - main

  push: 
    branches:
      - main
      - master 

jobs:

  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  backend:
    uses: ./.github/workflows/backend-ci.yml

  docker:
    needs:
      - frontend
      - backend

    uses: ./.github/workflows/docker-ci.yml